import esbuild from "esbuild";
import process from "process";
import tailwindPlugin from "esbuild-plugin-tailwindcss";
import nested from "postcss-nested";
import fs from "fs";
import path from "path";

// Plugin to copy HTML file to dist
const copyHtmlPlugin = {
    name: 'copy-html',
    setup(build) {
        build.onEnd(() => {
            const sourceHtml = 'src/browser-test/index.html';
            const destDir = 'dist/browser-test';
            const destHtml = path.join(destDir, 'index.html');

            // Ensure destination directory exists
            if (!fs.existsSync(destDir)) {
                fs.mkdirSync(destDir, { recursive: true });
            }

            fs.copyFileSync(sourceHtml, destHtml);
            console.log('Copied index.html to dist/browser-test/');
        });
    },
};

const banner =
    `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Browser test bundle for obsidian-tree-search
*/
`;

const prod = (process.argv[2] === "production");

const esbuildOptions = {
    banner: {
        js: banner,
    },
    entryPoints: ["src/browser-test/main.tsx"],
    bundle: true,
    // Don't externalize anything for browser bundle - bundle everything
    external: [],
    format: "iife",
    target: "es2020",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "dist/browser-test/bundle.js",
    plugins: [
        tailwindPlugin({
            output: "dist/browser-test/styles.css",
            postcssPlugins: {
                append: [
                    nested()
                ]
            }
        }),
        copyHtmlPlugin,
    ],
    // Define global variables for Node.js modules that might be referenced
    define: {
        'process.env.NODE_ENV': prod ? '"production"' : '"development"',
        'global': 'window',
    },
    // Handle Node.js built-ins that might be referenced
    platform: 'browser',
    // Alias obsidian module to our mock implementation
    alias: {
        'obsidian': './src/browser-test/mock-obsidian.ts'
    }
}

const context = await esbuild.context(
    { ...esbuildOptions }
);

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
    console.log('Watching browser test bundle...');
}
