import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import tailwindPlugin from "esbuild-plugin-tailwindcss";
import fs from "fs";
import path from "path";

// Plugin to copy files to dist
const copyFilesPlugin = {
	name: 'copy-files',
	setup(build) {
		build.onEnd(() => {
			const filesToCopy = ['.hotreload', 'manifest.json', 'manifest-beta.json'];
			filesToCopy.forEach(file => {
				fs.copyFileSync(file, path.join('dist', file));
			});
		});
	},
};

const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const esbuildOptions = {
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts", "src/view/styles.css"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins
	],
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outdir: "dist",
	entryNames: "[name]",
	plugins: [
		tailwindPlugin({ 
			output: "dist/styles.css"
		}),
		copyFilesPlugin,
	],
}

const context = await esbuild.context(
	{...esbuildOptions}
);

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
